void main() {
  writeln("<!doctype html>");
  writeln("<html><head><meta charset='utf-8'><title>Master Relay Settings</title>");
  writeln("<style>");
  writeln("body{font-family:Arial,Helvetica,sans-serif;background:#fff;color:#111;margin:18px;line-height:1.4}h1{font-size:20px;margin:0 0 7px}.box{max-width:720px;border:1px solid #888;padding:15px;background:#fafafa}.row{display:flex;align-items:center;gap:12px;margin:12px 0;padding:10px;border-top:1px solid #ddd}.row:first-of-type{border-top:0}.label{min-width:180px;font-weight:bold}.desc{flex:1;color:#444;font-size:12px}.control select{font:12px Arial,Helvetica,sans-serif;padding:3px 6px;min-width:72px}.ok{color:#166b16;font-weight:bold}.off{color:#8a1c1c;font-weight:bold}.muted{color:#666;font-size:11px}code{background:#eee;padding:1px 3px}.status{margin:10px 0;padding:8px;background:#fff;border:1px solid #bbb;font-size:12px}");
  writeln("</style></head><body>");
  writeln("<div class='box'><h1>KoLmafia Master Relay</h1>");
  writeln("<p>Use KoLmafia's normal <code>-run script-</code> relay dropdown to open this control page. No custom top-left launcher is added.</p>");
  writeln("<div class='row'><div class='label'>Master Relay</div><div class='desc'><b>On:</b> keep the existing right pane on KoLmafia's native integrated Chat / gCLI page, including its small top Chat / gCLI buttons. <b>Off:</b> restore the pre-relay right-pane page.</div><div class='control'><select id='kmr-enabled' onchange='kmrSetEnabled(this.value);'><option value='on'>On</option><option value='off'>Off</option></select></div></div>");
  writeln("<div class='row'><div class='label'>Split Chat Pane</div><div class='desc'><b>On:</b> keep integrated Chat / gCLI on the left and add a second live chat pane on the right. Drag the divider to resize it; its width is remembered. <b>Off:</b> use integrated mode at full right-pane width.</div><div class='control'><select id='kmr-split' onchange='kmrSetSplit(this.value);'><option value='off'>Off</option><option value='on'>On</option></select></div></div>");
  writeln("<div id='kmr-status' class='status'>Loading Master Relay state…</div>");
  writeln("<p class='muted'>The outer KoL frameset is never resized. Split mode divides only the existing right-side pane. A full reload of <code>game.php</code> removes the injected controller; select Master Relay from the relay dropdown again to reattach it.</p></div>");
  writeln("<script>");
  writeln("function kmrApi(){try{return top.KoLMasterRelay||null;}catch(e){return null;}}");
  writeln("function kmrSync(){var a=kmrApi(),s=document.getElementById('kmr-status');if(!a){s.className='status off';s.textContent='Master Relay controller is not attached.';return;}var st=a.status();document.getElementById('kmr-enabled').value=st.enabled?'on':'off';document.getElementById('kmr-split').value=st.split?'on':'off';s.className='status '+(st.enabled?'ok':'off');s.textContent='Relay '+(st.enabled?'ON':'OFF')+' · split '+(st.split?'ON':'OFF')+' · right pane '+(st.currentRightUrl||'unknown');}");
  writeln("function kmrSetEnabled(v){var a=kmrApi();if(a)a.setEnabled(v==='on');setTimeout(kmrSync,80);return false;}");
  writeln("function kmrSetSplit(v){var a=kmrApi();if(a)a.setSplit(v==='on');setTimeout(kmrSync,80);return false;}");
  writeln("(function(){try{var d=top.document;var existing=d.getElementById('kmr-master-script');var api=top.KoLMasterRelay;if(existing&&api&&api.version==='0.2.1'&&typeof api.refresh==='function'){api.refresh();setTimeout(kmrSync,40);return;}if(api&&typeof api.disable==='function'){try{api.disable();}catch(ignore){}}if(existing&&existing.parentNode)existing.parentNode.removeChild(existing);try{delete top.KoLMasterRelay;}catch(ignore2){top.KoLMasterRelay=null;}var s=d.createElement('script');s.id='kmr-master-script';s.src='/master_relay_launcher.js?v=0.2.1';s.onload=function(){if(top.KoLMasterRelay&&typeof top.KoLMasterRelay.refresh==='function')top.KoLMasterRelay.refresh();setTimeout(kmrSync,40);};(d.head||d.documentElement).appendChild(s);}catch(e){document.getElementById('kmr-status').textContent='Could not attach Master Relay: '+String(e);}})();");
  writeln("</script></body></html>");
}
